name: 'Slack Mention'
description: 'Provides a slack mention tag based on the input email address'
color: 'purple'
icon: 'at-sign'
labels: [slack, mention, CICD, pipeline, CI]
inputs:
  slack-token:
    description: 'The slack application token. (Must have `users:read` & `users:read.email` permissions.'
    required: true
  email:
    description: 'The email of the slack user you want to get a mention tag for'
    required: true
  default:
    description: 'The value to default should the email not exist in the slack workspace'
    default: ${{ github.pusher.email }}
    required: false
outputs:
  slack-mention-tag:
    description: 'The slack mention or default value'
  slack-user-id:
    description: 'The raw slack user ID value (defaults to null)'
runs:
  using: 'node20'
  main: 'index.js'
